# Copyright (c) 2026 Christoph Souris

import logging
import time
from dataclasses import dataclass

from pyc8y import CumulocityRestClient
from pyc8y.model.model_base import coerce_timedelta


logger = logging.getLogger(__name__)


@dataclass(frozen=True, slots=True)
class Credentials:
    tenant_id: str
    username: str
    password: str


class DeviceRegistryClient(CumulocityRestClient):
    """Cumulocity device registry client."""

    async def await_credentials(self, device_id: str, timeout: str = '60m', pause: str = '1s') -> Credentials:
        """Wait for device credentials.

        The device must have requested credentials already. This function
        awaits the request confirmation and returns the device-specific
        credentials generated by the Cumulocity platform.

        Args:
            device_id (str):  The external ID of the device
                (i.e. IMEI - NOT the Cumulocity ID)
            timeout (str):  How long to wait for the request to be confirmed.
                This is a formatted string in the form <int><unit>, accepted
                units are 'h' (hours), 'm' (minutes), 's' (seconds) and
                'ms' (milliseconds).
                A reasonable value for this depends on application.
            pause (str):  How long to pause between request confirmation checks
                This is a formatted string, see `timeout` parameter.

        Returns:
            Credentials object holding the device credentials

        Raises:
            TimeoutError:  if the request was not confirmed in time.

        See also: https://cumulocity.com/guides/users-guide/device-management/#connecting-devices
        """
        timeout_s = coerce_timedelta(timeout).seconds
        pause_s = coerce_timedelta(pause).seconds
        request_json = {'id': device_id}

        timeout_time = time.monotonic() + timeout_s
        while True:
            if time.monotonic() > timeout_time:
                raise TimeoutError
            logger.debug(f'Requesting device credentials for device id "{device_id}" ...')
            response = await (await self.session).post(
                '/devicecontrol/deviceCredentials',
                json=request_json,
                headers={'Content-Type': 'application/json', 'Accept': 'application/json'},
            )
            if response.status == 404:
                # This is the expected response until the device registration request got accepted
                # from within Cumulocity. It will be recognized as an inbound request, though and
                # trigger status 'pending' if it was 'awaiting connection'.
                time.sleep(pause_s)
            elif response.status == 201:
                response_json = await response.json()
                return Credentials(
                    tenant_id=response_json['tenantId'],
                    username=response_json['username'],
                    password=response_json['password'],
                )
            else:
                raise RuntimeError(f'Unexpected response code: {response.status} "{await response.text()}"')
