name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6.0.26
    - name: Install uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        python-version: '3.11'
    - name: Run ruff
      run: uv run ruff check src/pyc8y tests integration_tests samples
